#include "FuncionarioNaoExisteException.hpp"

const char* FuncionarioNaoExisteException::what(){

    return "Funcionario n√£o encontrado";
    
}
